
ALTER TABLE `npc_vendor` 
ADD COLUMN `CustomCost` ENUM('1_DISABLED','2_HONOR','3_ARENA','4_ITEM') DEFAULT '1_DISABLED' NOT NULL AFTER `VerifiedBuild`, 
ADD COLUMN `CustomValue` INT(10) UNSIGNED DEFAULT 0 NOT NULL AFTER `CustomCost`;
