/* Goblin */
DELETE FROM `playercreateinfo_action` WHERE `race` = '9';
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','1','0','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','1','72','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','1','73','78','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','1','74','20572','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','1','84','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','1','96','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','1','108','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','3','0','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','3','1','2973','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','3','2','75','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','3','11','20572','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','4','0','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','4','1','1752','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','4','2','2098','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','4','3','2764','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','4','4','20572','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','6','0','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','6','1','49576','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','6','2','45477','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','6','3','45462','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','6','4','45902','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','6','5','47541','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','6','10','20572','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','7','0','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','7','1','403','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','7','2','331','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','7','3','33697','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','9','0','686','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','9','1','687','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('9','9','2','33702','0');

-- ----------
-- ----------

/* Worgen */
DELETE FROM `playercreateinfo_action` WHERE `race` = '12';
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','1','0','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','1','72','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','1','73','78','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','1','82','59752','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','1','84','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','1','96','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','1','108','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','2','0','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','2','1','21084','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','2','2','635','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','2','11','59752','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','4','0','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','4','1','1752','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','4','2','2098','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','4','3','2764','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','4','11','59752','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','5','0','585','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','5','1','2050','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','5','11','59752','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','6','0','6603','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','6','1','49576','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','6','2','45477','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','6','3','45462','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','6','4','45902','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','6','5','47541','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','6','11','59752','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','8','0','133','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','8','1','168','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','8','11','59752','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','9','0','686','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','9','1','687','0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES('12','9','11','59752','0');
